name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Login
      run: docker login -u nozich --password ${{secrets.DOCKER_ACCESS_TOKEN}}

    - name: Build the Docker image
      run:
        pwd &&
        ls -lash &&
        whoami &&
        echo "node version $(node -v)" &&
        echo "npm version $(npm -v)" &&
        npm i -g zx@latest && echo "zx version $(zx -v)" &&
        curl -fsSL https://bun.sh/install | bash &&
        bun run ./push.mjs
