name: prod

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Docker Hub Production
        run: docker run --rm -v ./:/app nozich/bunode:latest zsh -c "bun run push.mjs"
